ordenIngreso_new:
    pattern:  /new
    defaults: { _controller: "BackendAdminBundle:OrdenIngreso:new" }

ordenIngreso_exportar:
    pattern:  /exportar
    defaults: { _controller: "BackendAdminBundle:OrdenIngreso:exportar" }
    
ordenIngreso_create:
    pattern:  /create
    defaults: { _controller: "BackendAdminBundle:OrdenIngreso:create" }
    requirements: { _method: post }

ordenIngreso_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendAdminBundle:OrdenIngreso:edit" }

ordenIngreso_procesa:
    pattern:  /{id}/procesa
    defaults: { _controller: "BackendAdminBundle:OrdenIngreso:procesa" }    

ordenIngreso_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendAdminBundle:OrdenIngreso:update" }
    requirements: { _method: post|put }

ordenIngreso_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendAdminBundle:OrdenIngreso:delete" }
    requirements: { _method: post|delete }
    
ordenIngreso_print:
    pattern:  /{id}/print
    defaults: { _controller: "BackendAdminBundle:OrdenIngreso:print" }


ordenIngreso_toprocesadoorden:
    pattern:  /toprocesadoorden
    defaults: { _controller: "BackendAdminBundle:OrdenIngreso:toProcesadoOrden" }    

ordenIngreso_togeneratecombo:
    pattern:  /togeneratecombo
    defaults: { _controller: "BackendAdminBundle:OrdenIngreso:toGenerateCombo" }    

ordenIngreso_togeneratecombomarca:
    pattern:  /togeneratecombomarca
    defaults: { _controller: "BackendAdminBundle:OrdenIngreso:toGenerateComboMarca" }    

ordenIngreso_toprocesadoingresos:
    pattern:  /toprocesadoingresos
    defaults: { _controller: "BackendAdminBundle:OrdenIngreso:toProcesadoIngresos" }  

ordenIngreso_toremoveingreso:
    pattern:  /toremoveingreso
    defaults: { _controller: "BackendAdminBundle:OrdenIngreso:toRemoveIngreso" }      

ordenIngreso:
    pattern:  /{search}
    defaults: { _controller: "BackendAdminBundle:OrdenIngreso:index" , search: '' }
