ordenIngresoParte_new:
    pattern:  /new
    defaults: { _controller: "BackendAdminBundle:OrdenIngresoParte:new" }

ordenIngresoParte_exportar:
    pattern:  /exportar
    defaults: { _controller: "BackendAdminBundle:OrdenIngresoParte:exportar" }
    
ordenIngresoParte_create:
    pattern:  /create
    defaults: { _controller: "BackendAdminBundle:OrdenIngresoParte:create" }
    requirements: { _method: post }

ordenIngresoParte_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendAdminBundle:OrdenIngresoParte:edit" }

ordenIngresoParte_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendAdminBundle:OrdenIngresoParte:update" }
    requirements: { _method: post|put }
    
ordenIngresoParte_procesa:
    pattern:  /{id}/procesa
    defaults: { _controller: "BackendAdminBundle:OrdenIngresoParte:procesa" }    

ordenIngresoParte_toaceptado:
    pattern:  /{id}/toaceptado
    defaults: { _controller: "BackendAdminBundle:OrdenIngresoParte:toAceptado" }    

ordenIngresoParte_torechazado:
    pattern:  /{id}/torechazado
    defaults: { _controller: "BackendAdminBundle:OrdenIngresoParte:toRechazado" }    

ordenIngresoParte_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendAdminBundle:OrdenIngresoParte:delete" }
    requirements: { _method: post|delete }
    
ordenIngresoParte_toprocesadoorden:
    pattern:  /toprocesadoorden
    defaults: { _controller: "BackendAdminBundle:OrdenIngresoParte:toProcesadoOrden" }    

ordenIngresoParte_togeneratecombo:
    pattern:  /togeneratecombo
    defaults: { _controller: "BackendAdminBundle:OrdenIngresoParte:toGenerateCombo" }    


ordenIngresoParte_toprocesadoingresos:
    pattern:  /toprocesadoingresos
    defaults: { _controller: "BackendAdminBundle:OrdenIngresoParte:toProcesadoIngresos" }    

ordenIngresoParte:
    pattern:  /{search}
    defaults: { _controller: "BackendAdminBundle:OrdenIngresoParte:index" , search: '' }
